/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import jakarta.persistence.EntityManagerFactory;
import org.example.dto.ClienteDTO;
import org.example.entity.Cliente;
import org.example.provider.ClienteProvider;
import org.example.repository.ClienteRepository;
import org.example.saga.SagaExecutor;
import org.example.utils.HibernateUtils;
import org.hibernate.Session;
import org.hibernate.envers.AuditReader;
import org.hibernate.envers.AuditReaderFactory;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class App implements RequestHandler<Map<String, String>, String> {

    public static void main(String[] args) {
        Map<String, String> temp = new HashMap<>();
        temp.put("nome","Jones");
        temp.put("telefone","27997418372");
        temp.put("email", "jonesvital@gmail.com");
        temp.put("rollback", "true");


        new App().handleRequest(temp, null);
    }

    public static ClienteRepository clienteRepository = new ClienteRepository();
    public static ClienteProvider clienteProvider = new ClienteProvider();
    public static SagaExecutor sagaExecutor = new SagaExecutor(clienteProvider);
    @Override
    public String handleRequest(Map<String, String> stringStringMap, Context context) {

        ClienteDTO clienteDTO = new ClienteDTO(stringStringMap);
        Cliente cliente = clienteRepository.buscarCliente(clienteDTO);

        if(stringStringMap.containsKey("rollback") && (stringStringMap.get("rollback").equals("true"))) {
            sagaExecutor.compensate(cliente);
        } else {
            cliente.setCreatedAt(new Date());
            clienteProvider.salvarCliente(cliente);
        }

        return null;
    }
}
