/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import org.example.dto.ClienteDTO;
import org.example.provider.ClienteProvider;
import org.example.repository.ClienteRepository;
import org.example.saga.SagaExecutor;

import java.util.HashMap;
import java.util.Map;

public class App implements RequestHandler<Map<String, String>, String> {

    public static void main(String[] args) {

        Map<String, String> temp = new HashMap<>();
        temp.put("nome","Jones");
        temp.put("telefone","27997418372");
        temp.put("email", "jonesvital@gmail.com");
        temp.put("rollback", "true");


        new App().handleRequest(temp, null);

    }

    public static ClienteProvider clienteProvider = new ClienteProvider();
    public static ClienteRepository clienteRepository = new ClienteRepository();
    public static SagaExecutor sagaExecutor = new SagaExecutor(clienteRepository);

    @Override
    public String handleRequest(Map<String, String> stringStringMap, Context context) {

        ClienteDTO clienteDTO = new ClienteDTO(stringStringMap);

        if(stringStringMap.containsKey("rollback") && (stringStringMap.get("rollback").equals("true"))) {
            sagaExecutor.compensate(clienteDTO);
        } else {
            clienteProvider.criarCliente(clienteDTO);
        }

        return null;
    }
}
